# Generated by Django 3.1.2 on 2020-10-20 06:24

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(default=1, verbose_name='Номер по порядку')),
                ('bigText', models.CharField(max_length=70, null=True, verbose_name='Заголовок на баннере (70 символов)')),
                ('smallText', models.CharField(max_length=200, null=True, verbose_name='Описание на баннере (200 символов)')),
                ('image', models.ImageField(blank=True, null=True, upload_to='slides/', verbose_name='Картинка для баннера (1920 x 660)')),
                ('buttonText', models.CharField(max_length=10, null=True, verbose_name='Надпись на первой кнопке')),
                ('buttonUrl', models.CharField(max_length=100, null=True, verbose_name='Ссылка с кнопки')),
                ('button1Text', models.CharField(max_length=10, null=True, verbose_name='Надпись на второй кнопке')),
                ('button1Url', models.CharField(max_length=100, null=True, verbose_name='Ссылка с второй кнопки')),
                ('isActive', models.BooleanField(default=True, verbose_name='Отображать ?')),
            ],
            options={
                'verbose_name': 'Баннер',
                'verbose_name_plural': 'Баннеры',
            },
        ),
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, null=True, verbose_name='Название статьи')),
                ('short_description', models.CharField(max_length=255, verbose_name='Краткое описание (255 символов)')),
                ('description', ckeditor_uploader.fields.RichTextUploadingField(null=True, verbose_name='Статья')),
                ('nameSlug', models.CharField(blank=True, editable=False, max_length=255, null=True)),
                ('image', models.ImageField(upload_to='post_img/', verbose_name='Изображение превью (360 x 240)')),
                ('pageH1', models.CharField(blank=True, max_length=255, null=True, verbose_name='Тег H1')),
                ('pageTitle', models.CharField(blank=True, max_length=255, null=True, verbose_name='Название страницы SEO')),
                ('pageDescription', models.CharField(blank=True, max_length=255, null=True, verbose_name='Описание страницы SEO')),
                ('pageKeywords', models.TextField(blank=True, null=True, verbose_name='Keywords SEO')),
                ('views', models.IntegerField(default=0, verbose_name='Просмотров')),
                ('isActive', models.BooleanField(default=True, verbose_name='Отображается?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Статья',
                'verbose_name_plural': 'Статьи',
            },
        ),
        migrations.CreateModel(
            name='Callback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='Нет данных', max_length=255, verbose_name='Имя')),
                ('phone', models.CharField(blank=True, default='Нет данных', max_length=255, verbose_name='Телефон')),
                ('email', models.CharField(blank=True, default='Нет данных', max_length=255, verbose_name='Почта')),
                ('service', models.CharField(blank=True, default='Нет данных', max_length=255, verbose_name='Услуга')),
                ('message', models.TextField(blank=True, default='Нет данных', verbose_name='Сообщение')),
                ('file', models.FileField(blank=True, null=True, upload_to='', verbose_name='Прикрепленный файл')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата заполнения')),
            ],
            options={
                'verbose_name': 'Форма заказа звонка',
                'verbose_name_plural': 'Формы заказа звонка',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer', models.CharField(blank=True, max_length=40, null=True, verbose_name='Название проекта')),
                ('nameSlug', models.CharField(blank=True, editable=False, max_length=255, null=True)),
                ('name', models.CharField(max_length=255, null=True, verbose_name='Заказчик ')),
                ('image', models.ImageField(blank=True, upload_to='project_img/', verbose_name='Изображение (360 x 240)')),
                ('town', models.CharField(blank=True, max_length=40, null=True, verbose_name='Город')),
                ('description', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Полное описание проекта')),
                ('pageH1', models.CharField(blank=True, max_length=255, null=True, verbose_name='Тег H1')),
                ('pageTitle', models.CharField(blank=True, max_length=255, null=True, verbose_name='Название страницы SEO')),
                ('pageDescription', models.CharField(blank=True, max_length=255, null=True, verbose_name='Описание страницы SEO')),
                ('pageKeywords', models.TextField(blank=True, null=True, verbose_name='Keywords SEO')),
            ],
            options={
                'verbose_name': 'Проект',
                'verbose_name_plural': 'Проекты',
            },
        ),
        migrations.CreateModel(
            name='SeoTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('indexTitle', models.CharField(blank=True, max_length=255, null=True, verbose_name='Тег Title для главной')),
                ('indexDescription', models.CharField(blank=True, max_length=255, null=True, verbose_name='Тег Description для главной')),
                ('indexKeywords', models.TextField(blank=True, null=True, verbose_name='Тег Keywords для главной')),
                ('servicesTitle', models.CharField(blank=True, max_length=255, null=True, verbose_name='Тег Title для страницы со всеми услугами')),
                ('servicesDescription', models.CharField(blank=True, max_length=255, null=True, verbose_name='Тег Description для страницы со всеми услугам')),
                ('servicesKeywords', models.TextField(blank=True, null=True, verbose_name='Тег Keywords для страницы со всеми услугам')),
                ('projectsTitle', models.CharField(blank=True, max_length=255, null=True, verbose_name='Тег Title для страницы со всеми проектами')),
                ('projectsDescription', models.CharField(blank=True, max_length=255, null=True, verbose_name='Тег Description для страницы со всеми проектами')),
                ('projectsKeywords', models.TextField(blank=True, null=True, verbose_name='Тег Keywords для страницы со всеми проектами')),
                ('contactTitle', models.CharField(blank=True, max_length=255, null=True, verbose_name='Тег Title для страницы контакты')),
                ('contactDescription', models.CharField(blank=True, max_length=255, null=True, verbose_name='Тег Description для страницы контакты')),
                ('contactKeywords', models.TextField(blank=True, null=True, verbose_name='Тег Keywords для страницы контакты')),
                ('aboutTitle', models.CharField(blank=True, max_length=255, null=True, verbose_name='Тег Title для страницы о компании')),
                ('aboutDescription', models.CharField(blank=True, max_length=255, null=True, verbose_name='Тег Description для страницы о компании')),
                ('aboutKeywords', models.TextField(blank=True, null=True, verbose_name='Тег Keywords для страницы о компании')),
                ('blogTitle', models.CharField(blank=True, max_length=255, null=True, verbose_name='Тег Title для страницы блог')),
                ('blogDescription', models.CharField(blank=True, max_length=255, null=True, verbose_name='Тег Description для страницы блог')),
                ('blogKeywords', models.TextField(blank=True, null=True, verbose_name='Тег Keywords для страницы блог')),
                ('yandexMetrika', models.TextField(blank=True, null=True, verbose_name='Код Яндекс метрики')),
                ('fbPixel', models.TextField(blank=True, null=True, verbose_name='Код пикселя')),
                ('yandexTAG', models.CharField(blank=True, max_length=255, null=True, verbose_name='Код подтверждения Яндекс')),
                ('googleTAG', models.CharField(blank=True, max_length=255, null=True, verbose_name='Код подтверждения google')),
                ('indexText', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Текст на главную')),
            ],
            options={
                'verbose_name': 'Теги и текста для статических страниц',
                'verbose_name_plural': 'Теги и текста для статических страниц',
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, null=True, verbose_name='Название услуги')),
                ('short_description', models.TextField(verbose_name='Краткое описание (380 символов)')),
                ('description', ckeditor_uploader.fields.RichTextUploadingField(null=True, verbose_name='Полное описание услуги')),
                ('isHomeVisible', models.BooleanField(db_index=True, default=True, verbose_name='Отображать на главной?')),
                ('nameSlug', models.CharField(blank=True, editable=False, max_length=255, null=True)),
                ('image', models.ImageField(upload_to='service_img/', verbose_name='Изображение превью (360 x 240)')),
                ('pageH1', models.CharField(blank=True, max_length=255, null=True, verbose_name='Тег H1')),
                ('pageSpecialText', models.CharField(blank=True, max_length=255, null=True, verbose_name='Специальное предложение')),
                ('pageTitle', models.CharField(blank=True, max_length=255, null=True, verbose_name='Название страницы SEO')),
                ('pageDescription', models.CharField(blank=True, max_length=255, null=True, verbose_name='Описание страницы SEO')),
                ('pageKeywords', models.TextField(blank=True, null=True, verbose_name='Keywords SEO')),
                ('price', models.IntegerField(default=0, verbose_name='Стоимость услуги')),
                ('views', models.IntegerField(default=0, verbose_name='Просмотров')),
                ('isActive', models.BooleanField(default=True, verbose_name='Активная услуга?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Услуга',
                'verbose_name_plural': 'Услуги',
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='review_img/', verbose_name='Отзыв')),
                ('image_small', models.CharField(blank=True, max_length=255, null=True)),
                ('service', models.ManyToManyField(null=True, related_name='review_img', to='pages.Service', verbose_name='Отзыв для услуг')),
            ],
            options={
                'verbose_name': 'Отзыв',
                'verbose_name_plural': 'Отзывы',
            },
        ),
        migrations.CreateModel(
            name='ProjectImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(null=True, upload_to='project_img/', verbose_name='Фото')),
                ('image_small', models.CharField(blank=True, default='', max_length=255)),
                ('project', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pages.project', verbose_name='Фото для проекта')),
            ],
            options={
                'verbose_name': 'Фото для проекта',
                'verbose_name_plural': 'Фото для проекта',
            },
        ),
    ]
