# Generated by Django 3.1.2 on 2020-10-20 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(default=1, verbose_name='Номер по порядку')),
                ('name', models.CharField(max_length=255, null=True, verbose_name='Название')),
                ('image', models.ImageField(null=True, upload_to='client_img/', verbose_name='Постоянный клиент')),
            ],
            options={
                'verbose_name': 'Постоянный клиент',
                'verbose_name_plural': 'Постоянный клиент',
            },
        ),
        migrations.RemoveField(
            model_name='banner',
            name='button1Text',
        ),
        migrations.RemoveField(
            model_name='banner',
            name='button1Url',
        ),
        migrations.AddField(
            model_name='project',
            name='short_description',
            field=models.TextField(null=True, verbose_name='Краткое описание (380 символов)'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='short_description',
            field=models.CharField(max_length=255, null=True, verbose_name='Краткое описание (255 символов)'),
        ),
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='project_img/', verbose_name='Изображение (360 x 240)'),
        ),
        migrations.AlterField(
            model_name='review',
            name='image',
            field=models.ImageField(null=True, upload_to='review_img/', verbose_name='Отзыв'),
        ),
        migrations.AlterField(
            model_name='service',
            name='short_description',
            field=models.TextField(null=True, verbose_name='Краткое описание (380 символов)'),
        ),
    ]
