# Generated by Django 3.1.2 on 2020-11-22 13:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_servicefeature_servicestep'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='is_home',
            field=models.BooleanField(default=False, verbose_name='Отображать на главной'),
        ),
        migrations.AlterField(
            model_name='servicefeature',
            name='service',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='features', to='pages.service', verbose_name='Услуга'),
        ),
        migrations.AlterField(
            model_name='servicestep',
            name='service',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='pages.service', verbose_name='Услуга'),
        ),
    ]
