# Generated by Django 3.1.2 on 2020-11-22 15:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_seotag_abouttext'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='project',
            name='town',
        ),
        migrations.RemoveField(
            model_name='projectimage',
            name='project',
        ),
        migrations.AddField(
            model_name='projectimage',
            name='image_before',
            field=models.BooleanField(default=False, verbose_name='До?'),
        ),
        migrations.AlterField(
            model_name='project',
            name='name',
            field=models.CharField(max_length=255, null=True, verbose_name='Название'),
        ),
        migrations.CreateModel(
            name='ProjectAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=255, null=True, verbose_name='Адрес')),
                ('project', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pages.project', verbose_name='Проект')),
            ],
        ),
        migrations.AddField(
            model_name='projectimage',
            name='project_address',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pages.projectaddress', verbose_name='Фото для проекта'),
        ),
    ]
