# Generated by Django 3.1.2 on 2020-11-23 05:32

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0007_auto_20201122_1839'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cert',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(null=True, upload_to='cert_img/', verbose_name='Сертификат')),
                ('image_small', models.CharField(blank=True, max_length=255, null=True)),
                ('is_home', models.BooleanField(default=False, verbose_name='Отображать на главной')),
            ],
            options={
                'verbose_name': 'Сертификат',
                'verbose_name_plural': 'Сертификаты',
            },
        ),
        migrations.RemoveField(
            model_name='review',
            name='service',
        ),
        migrations.AlterField(
            model_name='banner',
            name='bigText',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Заголовок на баннере (100 символов)'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='buttonText',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Надпись на первой кнопке'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='buttonUrl',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Ссылка с кнопки'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='smallText',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Описание на баннере (200 символов)'),
        ),
        migrations.AlterField(
            model_name='service',
            name='description',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Полное описание услуги'),
        ),
        migrations.AlterField(
            model_name='service',
            name='short_description',
            field=models.TextField(blank=True, null=True, verbose_name='Краткое описание (380 символов)'),
        ),
    ]
